name: llm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipywidgets>=8.1
  - jupyterlab_widgets
  - ipykernel
  - jupyterlab
  - requests
  - pandas
  - pyyaml
  - pip
  - pip:
      - tapipy
      - ckanapi
